dist: focal
sudo: true
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_extended_0.75.1_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.75.1_Linux-64bit.deb
  - udo apt-get install -y asciidoctor
script:
  - git submodule update --init
  - git submodule update --remote --merge
  - hugo version
  - hugo -v && cp public/bn/404.html public/404.html
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master
  name: Arafat Hasan
  email: opendoor.arafat@gmail.com
