dist: bionic
sudo: true
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_extended_0.75.1_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.75.1_Linux-64bit.deb
script:
  - git submodule update --init
  - git submodule update --remote --merge
  - hugo
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master
  committer_from_gh: true
