baseurl = "https://www.arafathasan.live/"

theme = "liva-hugo"
summaryLength = "10"
paginate = 6



defaultcontentlanguage = "en"
defaultContentLanguageInSubdir = true

# Enable robots.txt generation
enableRobotsTXT = true

googleAnalytics = "UA-178245243-1"

canonifyurls = true

#pygmentsstyle = "solarized-light"
#pygmentscodefences = true
#pygmentscodefencesguesssyntax = true

disqusShortname = "arafathasan"



#################### default parameters ################################

[params]
    keywords = "blog,developer,personal,resume,computer,technology,programmer,curriculum vitae"
    avatarurl = "/assets/images/avatar.jpg"

    favicon_32 = "/assets/images/knight-2-right-32x32.png"
    favicon_16 = "/assets/images/knight-2-right-16x16.png"

    dateformat = "January 2, 2006"

    hidecredits = false
    hidecopyright = false

    # rtl = false
    
    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    # colorscheme = "auto"

    math = true



    # Preloader
    [params.preloader]
        enable = true
        preloader = "" # use .png , .svg or .gif format

    # search
    [params.search]
        enable = false



    ############################# Plugins ##############################
    [params.plugins]

        # CSS Plugins
        [[params.plugins.css]]
            URL = "plugins/bootstrap/bootstrap.min.css"
        [[params.plugins.css]]
           URL = "plugins/slick/slick.css"
        [[params.plugins.css]]
           URL = "plugins/themify-icons/themify-icons.css"
        [[params.plugins.css]]
          URL = "plugins/venobox/venobox.css"

        # JS Plugins
        [[params.plugins.js]]
            URL = "plugins/jQuery/jquery.min.js"
        [[params.plugins.js]]
            URL = "plugins/bootstrap/bootstrap.min.js"
        [[params.plugins.js]]
            URL = "plugins/slick/slick.min.js"
        [[params.plugins.js]]
            URL = "plugins/venobox/venobox.min.js"
        [[params.plugins.js]]
            URL = "plugins/search/fuse.min.js"
        [[params.plugins.js]]
            URL = "plugins/search/mark.js"
        [[params.plugins.js]]
            URL = "plugins/search/search.js"



[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"


[languages]
    [languages.en]
        languagename = "English"
		title = "Arafat Hasan"
		contentDir = "content/en"
        languageCode = "en"

        [languages.en.outputs]
        home = ["HTML", "RSS", "JSON"]

        [languages.en.params]
            author = "Arafat Hasan"
            logo = "assets/images/logo.en.png"
            home = "OOOOOO"
            tagline = "Continuous Learner ⦁ Computer Nerd"
            description = "Arafat Hasan's personal website"
            location = "Rangpur, Bangladedsh"
            address = "House 36, Road 02, New Adarshapara, Rangpur-5402, Bangladedsh"
            mobile = "+8801521303510"
            email = "opendoor.arafat@gmail.com"
            copyright = "copyright &copy; 2020 Arafat Hasan"

            [languages.en.params.newsletter]
                enable = false
                title = "Join Our Newsletter"
                content = "Generally I share articles what i found insightfull with my newsletter subcribers"


        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "Home"
                identifier = "enHome"
                weight = 1
                url = "/en/"
                
            [[languages.en.menu.main]]
                name = "Tech Blog"
                identifier = "enTech"
                weight = 2
                url = "/en/prowritings/"


            [[languages.en.menu.main]]
                name = "Contact"
                identifier = "enContact"
                weight = 3
                url = "/en/contact"

            [[languages.en.menu.main]]
                name = "About"
                identifier = "enAbout"
                weight = 4
                url = "/en/about/"

            [[languages.en.menu.footer]]
                name = "About"
                identifier = "enAbout"
                weight = 1
                url = "/en/about/"


            [[languages.en.menu.footer]]
                name = "Contact"
                identifier = "enContact"
                weight = 5
                url = "/en/contact"

            [[languages.en.menu.footer]]
                name = "Policy"
                identifier = "enPolicy"
                weight = 6
                url = "/en/comment-policy/"


            ############################# social site ########################

            [[languages.en.params.social]]
                title = "facebook"
                icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
                link = "https://www.facebook.com/arafathasanjenin"

            [[languages.en.params.social]]
                title = "twitter"
                icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
                link = "https://twitter.com/Arafat_HJ"

            [[languages.en.params.social]]
                title = "stackoverflow"
                icon = " ti-stack-overflow " # themify icon : https://themify.me/themify-icons
                link = "https://stackoverflow.com/users/7829174/arafat-hasan"

            [[languages.en.params.social]]
                title = "github"
                icon = "ti-github" # themify icon : https://themify.me/themify-icons
                link = "https://www.github.com/arafat-hasan"

            [[languages.en.params.social]]
                title = "linkedin"
                icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
                link = "https://www.linkedin.com/in/arafat-hasan"



    [languages.bn]
        languagename = "বাংলা"
        title = "আরাফাত হাসান"
        contentDir = "content/bn"
        languageCode = "bn"
        
        [languages.bn.outputs]
        home = ["HTML", "RSS", "JSON"]

        [languages.bn.params]
            author = "আরাফাত হাসান"
            logo = "assets/images/logo.bn.png"
            home = "/bn"
            tagline = "ঋষি দরবেশ ⦁ শিখছি দিবারাত্র ⦁ আগন্তুক দর্শক"
            description = "আরাফাত হাসানের ওয়েবসাইট"
            location = "রংপুর, বাংলাদেশ"
            address = "বাড়ি ৩৬, রাস্তা ০২, নতুন আদর্শপাড়া, রংপুর-৫৪০২, বাংলাদেশ"
            mobile = "+8801521303510"
            email = "opendoor.arafat@gmail.com"
            copyright = "স্বত্ব &copy; ২০২০ আরাফাত হাসান"


            [languages.bn.params.newsletter]
                enable = false
                title = "আমার নিউজলেটারে সংযুক্ত হোন"
                content = "আমি নতুন যা পড়ছি বিশেষত গুরুত্বপুর্ণ কোন আর্টিকেলের লিংক আমি নিউজলেটারে শেয়ার করে থাকি"
    
        [languages.bn.menu]

            [[languages.bn.menu.main]]
                name = "নীড়পাতা"
                identifier = "bnHome"
                weight = 1
                url = "/bn/"

            [[languages.bn.menu.main]]
                name = "সব লেখা"
                identifier = "bnBlog"
                weight = 2
                url = "/bn/writings/"


            [[languages.bn.menu.main]]
                name = "প্রবন্ধ"
                parent = "bnBlog"
                identifier = "bnArticle"
                weight = 2
                url = "/bn/categories/প্রবন্ধ/"

            [[languages.bn.menu.main]]
                name = "গল্প"
                parent = "bnBlog"
                identifier = "bnStory"
                weight = 3
                url = "/bn/categories/গল্প/"

            [[languages.bn.menu.main]]
                name = "পেশাগত"
                parent = "bnBlog"
                identifier = "bnProf"
                weight = 4
                url = "/bn/categories/পেশাগত/"

            [[languages.bn.menu.main]]
                name = "অন্যান্য"
                parent = "bnBlog"
                identifier = "bnOther"
                weight = 5
                url = "/bn/categories/অন্যান্য/"

            [[languages.bn.menu.main]]
                name = "যোগাযোগ"
                identifier = "bnContact"
                weight = 3
                url = "/bn/contact/"

            [[languages.bn.menu.main]]
                name = "আমার সম্পর্কে"
                identifier = "bnAbout"
                weight = 4
                url = "/bn/about/"


            [[languages.bn.menu.footer]]
                name = "আমার সম্পর্কে"
                identifier = "bnAbout"
                weight = 1
                url = "/bn/about/"


            [[languages.bn.menu.footer]]
                name = "যোগাযোগ"
                identifier = "bnContact"
                weight = 5
                url = "/bn/contact/"

            [[languages.bn.menu.footer]]
                name = "নীতিমালা"
                identifier = "bnPolicy"
                weight = 6
                url = "/bn/comment-policy/"

            ############################# social site ########################

            [[languages.bn.params.social]]
                title = "ফেসবুক"
                icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
                link = "https://www.facebook.com/arafathasanjenin"

            [[languages.bn.params.social]]
                title = "টুইটার"
                icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
                link = "https://twitter.com/Arafat_HJ"

            [[languages.bn.params.social]]
                title = "স্ট্যাক ওভারফ্লো"
                icon = " ti-stack-overflow " # themify icon : https://themify.me/themify-icons
                link = "https://stackoverflow.com/users/7829174/arafat-hasan"

            [[languages.bn.params.social]]
                title = "গিটহাব"
                icon = "ti-github" # themify icon : https://themify.me/themify-icons
                link = "https://www.github.com/arafat-hasan"

            [[languages.bn.params.social]]
                title = "লিংকডইন"
                icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
                link = "https://www.linkedin.com/in/arafat-hasan"
