baseurl = ""

theme = "hugo-coder"


defaultcontentlanguage = "en"
defaultContentLanguageInSubdir = true

googleAnalytics = "UA-178245243-1"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "arafathasan"


[params]
    keywords = "blog,developer,personal,resume,computer,technology,programmer,curriculum vitae"
    avatarurl = "/assets/images/avatar.jpg"

    favicon_32 = "/assets/images/knight-2-right-32x32.png"
    favicon_16 = "/assets/images/knight-2-right-16x16.png"

    dateformat = "January 2, 2006"

    hidecredits = false
    hidecopyright = false

    rtl = false
    
    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    math = true
    custom_css = ["css/custom.css"]



[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"


[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/arafat-hasan/"
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 3
    url = "https://github.com/arafat-hasan/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 4
    url = "https://twitter.com/Arafat_HJ/"
[[params.social]]
    name = "Facebook"
    icon = "fa fa-facebook"
    weight = 5
    url = "https://www.facebook.com/OpenDoor.Arafat"
[[params.social]]
    name = "Stackoverflow"
    icon = "fa fa-stack-overflow"
    weight = 2
    url = "https://stackoverflow.com/users/7829174/arafat-hasan"


[languages]
    [languages.en]
        languagename = "English"
		title = "Arafat Hasan"

        [languages.en.params]
            author = "Arafat Hasan"
            info = "Continuous Learner ⦁ Computer Nerd"
            description = "Arafat Hasan's personal website"
            footercontent = "Want to talk? <a href='mailto:opendoor.arafat@gmail.com'>Email me!</a>"


        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "About"
                identifier = "enAbout"
                weight = 1
                url = "https://www.linkedin.com/in/arafat-hasan/"

            [[languages.en.menu.main]]
                name = "Blog"
                identifier = "enBlog"
                weight = 2
                url = "/posts/"

            [[languages.en.menu.main]]
                name = "Projects"
                identifier = "enProjects"
                weight = 3
                url = ""

            [[languages.en.menu.main]]
                name = "Contact me"
                identifier = "enContact"
                weight = 5
                url = ""


    [languages.bn]
        languagename = "বাংলা"
        title = "আরাফাত হাসান"

        [languages.bn.params]
            author = "আরাফাত হাসান"
            info = "ঋষি দরবেশ ⦁ ভড়ুয়া বাঙাল ⦁ বহিরাগত দর্শক"
            description = "আরাফাত হাসানের ওয়েবসাইট"
            footercontent = "আলাপ করতে চান? <a href='mailto:opendoor.arafat@gmail.com'>ইমেইল করুন!</a>"

    
        [languages.bn.menu]

            [[languages.bn.menu.main]]
                name = "জানুন"
                identifier = "bnAbout"
                weight = 1
                url = "https://www.linkedin.com/in/arafat-hasan/"

            [[languages.bn.menu.main]]
                name = "লেখা"
                identifier = "bnBlog"
                weight = 2
                url = "/posts/"

            [[languages.bn.menu.main]]
                name = "প্রকল্প"
                identifier = "bnProject"
                weight = 3
                url = ""

            [[languages.bn.menu.main]]
                name = "যোগাযোগ করুন"
                identifier = "bnContact"
                weight = 5
                url = ""
