

name: GitHub Pages

on:
  push:
    branches:
    - master
  schedule:
    # Run on the hour
    - cron: '0 * * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Checkout submodule
      uses: actions/checkout@v2.0.0
      with:
        token: ${{ secrets.GITHUBPAT }}
        repository: arafat-hasan/writings
        path: submodules/writings
        ref: 'master'

    - name: Install Ruby Dev
      run: sudo apt-get install ruby-dev

    - name: Install AsciiDoctor and Rouge
      run: sudo gem install asciidoctor rouge

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.79.0'
        extended: true

    - name: Build
      run: hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        # Without `keep_files` the `CNAME` file in the target repo will get removed
        # and the custom domain configured for GitHub pages will get dropped every
        # time the action runs…
        keep_files: true
        publish_dir: ./public

