

name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      uses: actions/checkout@v2.0.0
      with:
        token: ${{ secrets.GITHUBPAT }}
        repository: arafat-hasan/writings
        path: submodules/writings
        ref: 'master'

    - name: Checkout submodule
      uses: actions/checkout@v2.0.0
      with:
        token: ${{ secrets.GITHUBPAT }}
        repository: arafat-hasan/techNotes
        path: submodules/techNotes
        ref: 'master'

    - name: Checkout submodule
      uses: actions/checkout@v2.0.0
      with:
        token: ${{ secrets.GITHUBPAT }}
        repository: arafat-hasan/liva-hugo
        path: themes/liva-hugo
        ref: 'master'

    - name: Submodule update
      run: |
        git submodule init
        git submodule update

    - name: Install Ruby Dev
      run: sudo apt-get install ruby-dev

    - name: Install AsciiDoctor and Rouge
      run: sudo gem install asciidoctor rouge

    - name: Setup Hugo
      run: |
        curl -LO https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_extended_0.75.1_Linux-64bit.deb
        sudo dpkg -i hugo_extended_0.75.1_Linux-64bit.deb

    - name: Build
      run: hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        # Without `keep_files` the `CNAME` file in the target repo will get removed
        # and the custom domain configured for GitHub pages will get dropped every
        # time the action runs…
        keep_files: true
        publish_dir: ./public

